version: 1.2
workflows:
  - name: abra2Realigner
    subclass: WDL
    primaryDescriptorPath: /abra2.wdl
    testParameterFiles: 
    - /json/example_input_abra2.json
  - name: SNVJudgementFilter
    subclass: WDL
    primaryDescriptorPath: /Pipeline_variantJudgment.wdl
  - name: WGSVariantPipeline
    subclass: WDL
    primaryDescriptorPath: /WGS_variant_pipeline_main.wdl
    testParameterFiles: 
    - /json/WGS_SNV_CNV_variant_pipeline.json
  - name: Svaba
    subclass: WDL
    primaryDescriptorPath: /SvABA.wdl
    testParameterFiles: 
    - /json/svaba_example.json
  - name: MultiSNVCaller
    subclass: WDL
    primaryDescriptorPath: /SNV-MultiCaller.wdl
  - name: SNVGermline
    subclass: WDL
    primaryDescriptorPath: /SNV-GermlineMulti.wdl
    testParameterFiles: 
    - /json/SNV-Germline_inputs.json   
  - name: Oncokb
    subclass: WDL
    primaryDescriptorPath: /oncokb.wdl
    testParameterFiles: 
    - /json/oncokb_inputs.json
  - name: ClinicalReport
    subclass: WDL
    primaryDescriptorPath: /CombinedClinicalReport.wdl
  - name: ClinicalReportSNVOnly
    subclass: WDL
    primaryDescriptorPath: /CombinedClinicalReportModified.wdl
  - name: Manta
    subclass: WDL
    primaryDescriptorPath: /Manta1.6.wdl
    testParameterFiles: 
    - /json/Manta1.6_inputs.json
  - name: Strelka2
    subclass: WDL
    primaryDescriptorPath: /Strelka2.wdl
    testParameterFiles: 
    - /json/Strelka2_inputs.json
  - name: QCCheck
    subclass: WDL
    primaryDescriptorPath: /run_QC_checks.wdl
    testParameterFiles: 
    - /json/run_QC_checks_inputs.json
  - name: VEP104
    subclass: WDL
    primaryDescriptorPath: /VEP104.wdl
    testParameterFiles: 
    - /json/VEP104.hg19.inputs.json
    - /json/VEP104.hg38.inputs.json
  - name: FuncotateSegments
    subclass: WDL
    primaryDescriptorPath: /cnv_wdl/germline/modified_cnv_somatic_funcotate_seg_workflow.wdl
    testParameterFiles: 
    - /json/cnv_germline_funcotate_inputs.json
  - name: CNV_germline_case
    subclass: WDL
    primaryDescriptorPath: /cnv_wdl/germline/cnv_germline_case_workflow.wdl
  - name: AnnotSV
    subclass: WDL
    primaryDescriptorPath: /annotsv.wdl
    testParameterFiles: 
    - /json/annotsv.inputs.json
  - name: GRIDSS
    subclass: WDL
    primaryDescriptorPath: /gridss_task.wdl
  - name: bcftoolsFilter
    subclass: WDL
    primaryDescriptorPath: /bcftoolsFilter.wdl
  - name: downsample
    subclass: WDL
    primaryDescriptorPath: /downsampling.5.wdl
  - name: GATKSelectVariants
    subclass: WDL
    primaryDescriptorPath: /GATKselectVariants.wdl
  - name: CNVkit
    subclass: WDL
    primaryDescriptorPath: /cnvkit.wdl
  - name: Fastq2uBam
    subclass: WDL
    primaryDescriptorPath: /alignment/PairedFastQ2UnmappedBAM.wdl
  - name: WGSAlignment
    subclass: WDL
    primaryDescriptorPath: /alignment/WGSAlignmentPipeline.wdl
  - name: FastQC
    subclass: WDL
    primaryDescriptorPath: /FastQC.wdl
    testParameterFiles: 
    - /json/fastqc.json
  - name: SamtoolsCoverageMapping
    subclass: WDL
    primaryDescriptorPath: /Samtools_Coverage_MapStats.wdl
  - name: wgsMetrics
    subclass: WDL
    primaryDescriptorPath: /wgsmetrics.wdl
    testParameterFiles: 
    - /json/wgsmetrics.json
  - name: jointGenotyping
    subclass: WDL
    primaryDescriptorPath: /jointGenotyping/JointGenotyping.wdl
  - name: star
    subclass: WDL
    primaryDescriptorPath: /run_star.wdl
    testParameterFiles: 
    - /json/star2.6.json
  - name: kallisto
    subclass: WDL
    primaryDescriptorPath: /kallisto-workflow.wdl
    testParameterFiles: 
    - /json/kallisto.json
  - name: RSeQC
    subclass: WDL
    primaryDescriptorPath: /RSeQC.wdl
    testParameterFiles: 
    - /json/rseqc.json
  - name: WGS_Germline_pipeline
    subclass: WDL
    primaryDescriptorPath: /WGS_Germline_Pipeline.wdl
  - name: STARFusion
    subclass: WDL
    primaryDescriptorPath: /STARfusion.wdl
  - name: pisces
    subclass: WDL
    primaryDescriptorPath: /pisces_parallel.wdl